name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-qc"
database_id = "8c16b363-ae04-442d-a6f2-22daa8cf6895"
